learnest/core/urls.py
from django.urls import path
from .views import logout, inicio

urlpatterns = [
    #path('', HomePageView.as_view(), name="home"),
    #path('sample/', SamplePageView.as_view(), name="sample"),
    path('logout/', logout, name="logout"),
    path('inicio/', inicio, name="inicio"),
]

learnest/pages/urls.py
from django.urls import path
from .views import PageListView, PageDetailView, PageCreate, PageUpdate, PageDelete

pages_patterns = ([
    path('', PageListView.as_view(), name='pages'),
    path('<int:pk>/<slug:slug>/',
         PageDetailView.as_view(), name='page'),
    path('create/', PageCreate.as_view(), name="create"),
    path('update/<int:pk>/', PageUpdate.as_view(), name="update"),
    path('delete/<int:pk>/', PageDelete.as_view(), name="delete"),
], 'pages'
)

learnest/webplayground/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from pages.urls import pages_patterns

urlpatterns = [
    path('home/', include('core.urls')),
    path('admin/', admin.site.urls),
    path('', include(pages_patterns)),
]

learnest/core/models.py
from django.db import models

# Create your models here.

learnest/pages/models.py
from django.db import models


class Page(models.Model):
    title = models.CharField(verbose_name="Título", max_length=200)
    content = models.CharField(verbose_name="Contenido", max_length=400)
    link = models.URLField(
        verbose_name="Link de pago", max_length=200)
    THEME_CHOICES = (
        ('navega_panama', 'Panama'),
        ('navega_rep_dom', 'Dominicana'),
        ('navega_guatemala', 'Guatemala'),
    )
    client = models.CharField(verbose_name="Cliente",
                              max_length=20, choices=THEME_CHOICES)
    price = models.DecimalField(
        max_digits=8,
        decimal_places=2)
    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(
        auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "página"
        verbose_name_plural = "páginas"
        ordering = ['title', 'client']

    def __str__(self):
        return self.title

learnest/core/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.contrib.auth import logout as auth_logout
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse


class HomePageView(TemplateView):

    template_name = "core/home.html"

    # Redefinimos el diccionario de Contexto
    def get(self, request):
        # el 3er parametro es el dic de contexto
        return render(request, self.template_name, {'title': 'Mi superweb playground'})


''' 
    Otra forma 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Mi superweb Playground"
        return context
'''


class SamplePageView(TemplateView):

    template_name = "core/sample.html"


def logout(request):
    auth_logout(request)
    return render(request, 'core/base.html')


def inicio(request):
    return HttpResponseRedirect(
        reverse('core/base.html',
                args=[request.user.username]))

learnest/pages/views.py
from django.urls import reverse, reverse_lazy
from .models import Page
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib import auth
from django.shortcuts import render

# Create your views here.


class PageListView(ListView):
    model = Page


class PageDetailView(DetailView):
    model = Page


class PageCreate(CreateView):
    model = Page
    fields = ['title', 'content', 'order']
    success_url = reverse_lazy('pages:pages')


class PageUpdate(UpdateView):
    model = Page
    fields = ['title', 'content', 'order']
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('pages:pages')

    def get_success_url(self):
        return reverse_lazy('pages:update', args=[self.object.id]) + '?ok'


class PageDelete(DeleteView):
    model = Page
    success_url = reverse_lazy('pages:pages')

learnest/core/templates/core/base.html
<script> 
    var url= "http://127.0.0.1:8000/admin/"; 
    window.location = url; 
</script> 

learnest/core/templates/core/base_2.html
<!DOCTYPE html>
<html lang="en">

    <head><meta http-equiv="Content-Type" content="text/html; charset=euc-jp">
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
       <title>{% block title %}{% endblock %}</title>
    {% load static %}

        <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">

<link rel="stylesheet" href="{% static 'core/css/index.css' %}">
<link rel="stylesheet" href="{% static 'core/css/navbar.css' %}">
<link rel="stylesheet" href="{% static 'core/css/normalize.min.css' %}">
<link rel="stylesheet" href="{% static 'core/css/font-awesome.css' %}">
<link rel="stylesheet" href="{% static 'core/css/carousel.css' %}">
<link rel="stylesheet" href="{% static 'core/css/style.css' %}"> 
<link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">

<link rel="stylesheet" href="{% static 'core/owlcarousel/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'core/owlcarousel/owl.theme.default.min.css' %}">


    </head>

    <body>
      <nav class="navbar navbar-default heavy" id="sticky_side_nav">
    <div class="sticky_side_inner">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <label id="mobile_menu_toggle" class="navbar-toggle btn btn-default" for="mobile_menu_checkbox"><span
                    class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span></label>

            <div class="contact mobile hidden-lg hidden-md hidden-sm">

                <div class="pull-left" style="width:40%">
                    <a href="index.php">
                        <img src="{% static 'core/img/logo_final.png' %}" alt="" style="width: 100%;padding: 10px;">
                    </a>
                </div>
            </div>

        </div>
        <input type="checkbox" id="mobile_menu_checkbox" class="hidden" name="mobile_menu_checkbox">
        <div id="sticky_side_nav_inner">
            <label class="mobile_menu_overlay" for="mobile_menu_checkbox"></label>
            <ul class="nav navbar-nav hidden-xs">

                <li class="close visible-xs"><label for="mobile_menu_checkbox" style="font-size: 24px !important;"><span
                            class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span></label></li>
                <li class="ml-5">
                    <a href="index.php">
                        <span class="hidden-xs " aria-hidden="true">
                            <img src="{% static 'core/img/logo_final.png' %}" alt="" style="height: 7vh">
                        </span>
                        <span class="home visible-xs">Home</span>
                    </a>
                </li>
                <!--
                <li class="dropdown fl-right mr-5" style="margin-top: 1%">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"
                        style="    padding-right: 0;">
                        <img src="img/formas/facebook.png" alt="" style="width:32px">
                    </a>

                </li>
   -->
                <li class="dropdown fl-right mt-1-5">
                    <a href="{% url 'logout' %}" class="dropdown-toggle" role="button" aria-expanded="false">
                        Cerrar Sesión
                    </a>
                </li>
                <!--
                <li class="dropdown fl-right mt-1-5">
                    <a href="#nosotros" class="dropdown-toggle" role="button" aria-expanded="false">
                        Nosotros</a>
                </li>
                <li class="dropdown fl-right mt-1-5">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                        aria-expanded="false">Servicios</a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="corblock.php">Corblock</a></li>
                        <li><a href="simple.php">Simple</a></li>
                    </ul>
                </li>
             -->
            </ul>

            <!-- MOBILE
            <ul class="nav navbar-nav visible-xs">
                <li class="close visible-xs"><label for="mobile_menu_checkbox" style="font-size: 24px !important;"><span
                            class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span></label></li>
                <li>
                    <a href="index.php">
                        <span class="hidden-xs " aria-hidden="true">
                            <img src="img/logo_final.png" alt="" style="height: 7vh">
                        </span>
                        <span class="home visible-xs">Home</span>
                    </a>
                </li>
                <li class="hidden-xs">
                    <a href=" #" class="dropdown-toggle" role="button" aria-expanded="false">
                        <img src="img/formas/facebook.png" alt="" style="width:32px">
                    </a>

                </li>
                <li>
                    <a href="#formulario" class="dropdown-toggle" role="button" aria-expanded="false">
                        Formulario</a>

                </li>
                <li>
                    <a href="#nosotros" class="dropdown-toggle" role="button" aria-expanded="false">
                        Nosotros</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                        aria-expanded="false">Servicios</a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="corblock.php">Corblock</a></li>
                        <li><a href="simple.php">Simple</a></li>
                    </ul>
                </li>
                <li class="visible-xs">
                    <a href=" #" class="dropdown-toggle" data-toggle="" role="button" aria-expanded="false">
                        <img src="img/formas/facebook.png" alt="" style="width:32px">
                    </a>

                </li>
            </ul>
        </div>/.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
  {% block content %}{% endblock %}


        <script src="{% static 'core/js/jquery.min.js' %}"></script>
<script src="{% static 'core/js/bootstrap.min.js' %}"></script>
<script src="{% static 'core/js/index.js' %}"></script>        <!--OWL-->
        <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/owl.carousel.min.js"></script>
        <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/jquery-mousewheel/3.1.13/jquery.mousewheel.min.js"></script>
        <script type="text/javascript">
        var owl = $('.owl-carousel');
        owl.owlCarousel({
            loop: true,
            nav: true,
            items: 2,
            navText: [
                "<img src='img/formas/felcha-hor.png' style='filter: invert(1); transform: rotate(180deg)'>",
                "<img src='img/formas/felcha-hor.png' style='filter: invert(1);'>"
            ],
            responsive: {
                0: {
                    items: 1.4,
                    nav: true
                },
                600: {
                    items: 3,
                    nav: false
                },
                1000: {
                    items: 5,
                    nav: true,
                    loop: false
                }
            }
        });
     
        /*ITEM ACTIVO NAV*/

        function verifica(ident) {

            switch (ident) {
                case 1: {
                    $("#elearning-ac").css({
                        background: "#EDF0F9"
                    });
                    $("#reforzamiento-ac").css({
                        background: "#fff"
                    });
                    $("#aumentada-ac").css({
                        background: "#fff"
                    });
                    $("#virtual-ac").css({
                        background: "#fff"
                    });
                    $("#chatbot-ac").css({
                        background: "#fff"
                    });
                    break;
                }
                case 2: {
                    $("#elearning-ac").css({
                        background: "#fff"
                    });
                    $("#reforzamiento-ac").css({
                        background: "#EDF0F9"
                    });
                    $("#aumentada-ac").css({
                        background: "#fff"
                    });
                    $("#virtual-ac").css({
                        background: "#fff"
                    });
                    $("#chatbot-ac").css({
                        background: "#fff"
                    });
                    break;
                }
                case 3: {
                    $("#elearning-ac").css({
                        background: "#fff"
                    });
                    $("#reforzamiento-ac").css({
                        background: "#fff"
                    });
                    $("#aumentada-ac").css({
                        background: "#EDF0F9"
                    });
                    $("#virtual-ac").css({
                        background: "#fff"
                    });
                    $("#chatbot-ac").css({
                        background: "#fff"
                    });
                    break;
                }
                case 4: {
                    $("#elearning-ac").css({
                        background: "#fff"
                    });
                    $("#reforzamiento-ac").css({
                        background: "#fff"
                    });
                    $("#aumentada-ac").css({
                        background: "#fff"
                    });
                    $("#virtual-ac").css({
                        background: "#EDF0F9"
                    });
                    $("#chatbot-ac").css({
                        background: "#fff"
                    });
                    break;
                }
                case 5: {
                    $("#elearning-ac").css({
                        background: "#fff"
                    });
                    $("#reforzamiento-ac").css({
                        background: "#fff"
                    });
                    $("#aumentada-ac").css({
                        background: "#fff"
                    });
                    $("#virtual-ac").css({
                        background: "#fff"
                    });
                    $("#chatbot-ac").css({
                        background: "#EDF0F9"
                    });
                    break;
                }
            }

        }
        </script>

        
    </body>

</html>

learnest/core/templates/core/home.html
{% extends 'core/base_2.html' %}
{% load static %}
{% block title %}Inicio de Sesión{% endblock %}
{% block content %}
        <div class="container-fluid">
            <div class="row  margin-tp">
                <div class="col-md-2">

                </div>
                <div class="col-md-8">
                    <h3 class="Gilroy-Bold center">
                        Asociados Comerciales
                    </h3>
                    <form action="{% url 'pages:pages' %}" method="get">
                        <div class="container-fluid">
                            <div class="row center caja-box">
                                <input name="user" class="campo-l light" type="text" placeholder="Usuario">
                                <input name="pass" class="campo-l light" type="password" placeholder="Contraseña">
                                <button class="btn-2 Gilroy-Bold blanco">
                                    Entrar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-md-2">

                </div>
            </div>
        </div>
{% endblock %}
  
  
  

learnest/core/templates/core/home_2.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Inicio de Sesión{% endblock %}
{% block content %}
<nav class="navbar navbar-default heavy" id="sticky_side_nav">
    <div class="sticky_side_inner">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <label id="mobile_menu_toggle" class="navbar-toggle btn btn-default" for="mobile_menu_checkbox"><span
                    class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span></label>

            <div class="contact mobile hidden-lg hidden-md hidden-sm">

                <div class="pull-left" style="width:40%">
                    <a href="index.php">
                        <img src="img/logo_final.png" alt="" style="width: 100%;padding: 10px;">
                    </a>
                </div>
            </div>

        </div>
        <input type="checkbox" id="mobile_menu_checkbox" class="hidden" name="mobile_menu_checkbox">
        <div id="sticky_side_nav_inner">
            <label class="mobile_menu_overlay" for="mobile_menu_checkbox"></label>
            <ul class="nav navbar-nav hidden-xs">

                <li class="close visible-xs"><label for="mobile_menu_checkbox" style="font-size: 24px !important;"><span
                            class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span></label></li>
                <li class="ml-5">
                    <a href="index.php">
                        <span class="hidden-xs " aria-hidden="true">
                            <img src="img/logo_final.png" alt="" style="height: 7vh">
                        </span>
                        <span class="home visible-xs">Home</span>
                    </a>
                </li>
               
            </ul>

          
    </div>
</nav>
        <div class="container-fluid">
            <div class="row  margin-tp">
                <div class="col-md-2">

                </div>
                <div class="col-md-8">
                    <h3 class="Gilroy-Bold center">
                        Asociados Comerciales
                    </h3>
                    <form action="panel.php" method="POST">
                        <div class="container-fluid">
                            <div class="row center caja-box">
                                <input name="user" class="campo-l light" type="text" placeholder="Usuario">
                                <input name="pass" class="campo-l light" type="password" placeholder="Contraseña">
                                <button class="btn-2 Gilroy-Bold blanco">
                                    Entrar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-md-2">

                </div>
            </div>
        </div>
{% endblock %}
  
  
  

learnest/core/templates/core/sample.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Página{% endblock %}
{% block content %}
<main role="main">
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-md-3">
        <img src="{% static 'core/img/placeholder.png' %}" class="img-fluid"/>
      </div>
      <div class="col-md-6 mt-3">
        <h3>Página de prueba</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce hendrerit nibh vel faucibus auctor. 
          Phasellus non arcu dictum, porttitor orci sed, maximus ligula. Duis mollis pulvinar tempor. 
          Cras ex nisl, fringilla ut rhoncus a, vestibulum ac turpis.</p>
      </div>
    </div>
  </div>
</main>
{% endblock %}

learnest/pages/templates/pages/home.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Inicio de Sesión{% endblock %}
{% block content %}
<nav class="navbar navbar-default heavy" id="sticky_side_nav">
    <div class="sticky_side_inner">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <label id="mobile_menu_toggle" class="navbar-toggle btn btn-default" for="mobile_menu_checkbox"><span
                    class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span></label>

            <div class="contact mobile hidden-lg hidden-md hidden-sm">

                <div class="pull-left" style="width:40%">
                    <a href="index.php">
                        <img src="img/logo_final.png" alt="" style="width: 100%;padding: 10px;">
                    </a>
                </div>
            </div>

        </div>
        <input type="checkbox" id="mobile_menu_checkbox" class="hidden" name="mobile_menu_checkbox">
        <div id="sticky_side_nav_inner">
            <label class="mobile_menu_overlay" for="mobile_menu_checkbox"></label>
            <ul class="nav navbar-nav hidden-xs">

                <li class="close visible-xs"><label for="mobile_menu_checkbox" style="font-size: 24px !important;"><span
                            class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span></label></li>
                <li class="ml-5">
                    <a href="index.php">
                        <span class="hidden-xs " aria-hidden="true">
                            <img src="img/logo_final.png" alt="" style="height: 7vh">
                        </span>
                        <span class="home visible-xs">Home</span>
                    </a>
                </li>
               
            </ul>

          
    </div>
</nav>
        <div class="container-fluid">
            <div class="row  margin-tp">
                <div class="col-md-2">

                </div>
                <div class="col-md-8">
                    <h3 class="Gilroy-Bold center">
                        Asociados Comerciales
                    </h3>
                    <form action="panel.php" method="POST">
                        <div class="container-fluid">
                            <div class="row center caja-box">
                                <input name="user" class="campo-l light" type="text" placeholder="Usuario">
                                <input name="pass" class="campo-l light" type="password" placeholder="Contraseña">
                                <button class="btn-2 Gilroy-Bold blanco">
                                    Entrar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-md-2">

                </div>
            </div>
        </div>
{% endblock %}
  
  
  

learnest/pages/templates/pages/includes/pages_menu.html
{% if request.user.is_staff %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <span class="navbar-brand" href="#"><i>Administrar</i></span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nep" aria-controls="nep" aria-expanded="false">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nep">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="#"><i>Crear página</i></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pages:pages' %}"><i>Listar páginas</i></a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% endif %}

learnest/pages/templates/pages/page_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Borrar página{% endblock %}
{% block content %}
{% include 'pages/includes/pages_menu.html'%}
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <div>
            <form action="" method="post">{% csrf_token %}
                <p>¿Estás seguro de que quieres borrar "{{ object }}"?</p>
                <input type="submit" value="Sí, borrar la página" />
            </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

learnest/pages/templates/pages/page_list.html
{% extends 'core/base_2.html' %}
{% load static %}
{% block title %}Páginas{% endblock %}
{% block content %}
{% include 'pages/includes/panel_menu.html'%}
{% if user.is_authenticated %}
<div class="container">
    <div class="row">
   
      {% for page in page_list|dictsort:"id" reversed %}
       {% if page.get_client_display  == request.user.username %}
        <div class="tab-content" id="v-pills-tabContent">
            <div class="tab-pane active " id="elearning" role="tabpanel" aria-labelledby=elearning>
                <div class="col-12 servicio " style=" ">
                    <div class="container-fluid">
                        <div class="row equal">
                            <div class="col-md-3 height-mob"
                                style=" background: url({% static 'core/img/servicios/servicio.png' %})">
                            </div>
                            <div class="col-md-5" style="padding:0 3%">
                                <h4 class="Gilroy-Bold">{{page.title}}</h4>
                                <p class="light mt-5">
                                {{page.content|striptags|safe|truncatechars:"200"}}</p>

                                <div class="container-fluid " style="padding: 0">
                                    <div class="">
                                        <div class="col-md-6" style="padding:0">
                                            <p class="light left celeste">
                                               15 clases divertidas
                                            </p>
                                        </div>
                                        <div class="col-md-6" style="padding:0">
                                            <p class="light left celeste">
                                                Duración: 10hs
                                            </p>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-4">
                            
                                <h4 class="Gilroy-Bold right">{{page.price}}</h4>
                                
                               <!-- <h4 class="Gilroy-Bold right">Consulte</h4>-->


                                <p class="descr light celeste right mt-5" style="margin-left:50%">
                                    Si eres asociado comercial accede a la plataforma de pago haciendo click en
                                    comprar
                                </p>

                                <div class="caja-btn">
                                    <button class="btn-1 Gilroy-Bold gris">
                                        Ver Detalles
                                    </button>
                                    <a href="{{page.link}}">
                                    <input class="btn-2 Gilroy-Bold blanco" type="submit" name="submit"
                                            value="Pagar" />
                                            </a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    {% endfor %}

    </div>
</div>
{% else %}
<script> 
    var url= "http://127.0.0.1:8000/admin/"; 
    window.location = url; 
</script> 
        {% endif %}

{% endblock %}

learnest/pages/templates/pages/panel.html
{% extends 'core/base_2.html' %}
{% load static %}
{% block title %}Páginas{% endblock %}
{% block content %}
{% include 'pages/includes/panel_menu.html'%}

<div class="container">
    <div class="row">
      {% for page in page_list|dictsort:"id" reversed %}
        <div class="tab-content" id="v-pills-tabContent">
            <div class="tab-pane active " id="elearning" role="tabpanel" aria-labelledby=elearning>
                <div class="col-12 servicio " style=" ">
                    <div class="container-fluid">
                        <div class="row equal">
                            <div class="col-md-3 height-mob"
                                style=" background: url(img/servicios/servicio.png)">
                            </div>
                            <div class="col-md-5" style="padding:0 3%">
                                <h4 class="Gilroy-Bold">{{page.title}}</h4>
                                <p class="light mt-5">
                                {{page.content|striptags|safe|truncatechars:"200"}}</p>

                                <div class="container-fluid " style="padding: 0">
                                    <div class="">
                                        <div class="col-md-6" style="padding:0">
                                            <p class="light left celeste">
                                                15 clases divertidas
                                            </p>
                                        </div>
                                        <div class="col-md-6" style="padding:0">
                                            <p class="light left celeste">
                                                Duración: 10hs
                                            </p>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-4">
                            
                                <h4 class="Gilroy-Bold right">{{page.precio}}</h4>
                                
                               <!-- <h4 class="Gilroy-Bold right">Consulte</h4>-->


                                <p class="descr light celeste right mt-5" style="margin-left:50%">
                                    Si eres asociado comercial accede a la plataforma de pago haciendo click en
                                    comprar
                                </p>

                                <div class="caja-btn">
                                    <button class="btn-1 Gilroy-Bold gris">
                                        Ver Detalles
                                    </button>
                                    <a href="{{page.link}}">
                                    <input class="btn-2 Gilroy-Bold blanco" type="submit" name="submit"
                                            value="Pagar" />
                                            </a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

    </div>
</div>
{% endblock %}